In [1]:
import numpy as np

In [2]:
#1. 運用上列array計算反矩陣，乘上原矩陣，並觀察是否為單位矩陣?
array1 = np.array([[10, 8], [3, 5]])

In [4]:
A = np.linalg.inv(array1)

In [5]:
np.matmul(A, array1)

array([[1.00000000e+00, 5.55111512e-17],
       [0.00000000e+00, 1.00000000e+00]])

In [6]:
#答案為單位矩陣

In [8]:
#2. 運用上列array計算特徵值、特徵向量?
array1 = np.array([[10, 8], [3, 5]])

In [9]:
w, v = np.linalg.eig(array1)

In [10]:
w  # eigenvalues

array([13.,  2.])

In [11]:
v  #eigenvectors

array([[ 0.93632918, -0.70710678],
       [ 0.35112344,  0.70710678]])

In [12]:
#3. 運用上列array計算SVD?

In [13]:
u, s, vh = np.linalg.svd(array1)

In [14]:
u

array([[-0.91663818, -0.39971796],
       [-0.39971796,  0.91663818]])

In [15]:
s

array([13.94721714,  1.86417116])

In [16]:
vh

array([[-0.74319741, -0.6690722 ],
       [-0.6690722 ,  0.74319741]])